IMAGE_NAME="bento/ubuntu-20.04"
NODES = 3
Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.vm.provider :virtualbox do |vb|
    vb.memory = 2048
    vb.cpus = 2
  end
    (1..NODES).each do |i|
      config.vm.define "shard-#{i}" do |clickhouse|
        config.vm.box = IMAGE_NAME
        # TODO: make IPs configurable - right now range matches block [clickhouse-cluster] in
        # hack/inventory/inventory_dev file
        clickhouse.vm.network "public_network", ip: "192.168.0.#{ i+50 }"
        clickhouse.vm.hostname = "shard-#{i}"
      end
    end
end
