IMAGE_NAME="bento/ubuntu-20.04"
Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.vm.provider :virtualbox do |vb|
    vb.memory = 512
    vb.cpus = 1
  end

      config.vm.define "zk-0" do |zk|
        config.vm.box = IMAGE_NAME
        zk.vm.network "public_network", ip: ENV['IP_ZK_NODE']
        zk.vm.hostname = "zk-node"
      end
end
