IMAGE_NAME="bento/ubuntu-16.04"
Vagrant.configure("2") do |config|
  config.vm.box = IMAGE_NAME
  config.ssh.insert_key = false
  config.vm.provider :virtualbox do |vb|
    vb.memory = 1024
    vb.cpus = 1
  end
  config.vm.define "clickhouse" do |clickhouse|
    clickhouse.vm.network :public_network, :bridge => 'wlan0', :use_dhcp_assigned_default_route => true, ip: "192.168.0.40"
  end
end
