IMAGE_NAME="bento/ubuntu-20.04"
Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.vm.provider :virtualbox do |vb|
    vb.memory = 512
    vb.cpus = 1
  end

      config.vm.define "zk-0" do |zk|
        config.vm.box = IMAGE_NAME
        # TODO: make the IP address configurable
        zk.vm.network "public_network", ip: "192.168.0.55"
        zk.vm.hostname = "zk-0"
      end
end
