IMAGE_NAME="bento/ubuntu-20.04"
Vagrant.configure("2") do |config|
  config.vm.box = IMAGE_NAME
  config.ssh.insert_key = false
  config.vm.provider :virtualbox do |vb|
    vb.memory = 1024
    vb.cpus = 1
  end
  config.vm.define "clickhouse" do |clickhouse|
    # TODO: allow this IP to be configurable
    clickhouse.vm.network "public_network", ip: "192.168.0.25"
  end
end
